From 8bf2af217739b012c74a9cf459101fee2e0daba9 Mon Sep 17 00:00:00 2001
From: Jan Chren <dev.rindeal+github.com@gmail.com>
Date: Mon, 18 Dec 2017 20:59:17 +0100
Subject: [PATCH] make `Makefile` a bit more packaging friendly

---
 Makefile | 44 +++++++++++++++++++++++++++++++-------------
 1 file changed, 31 insertions(+), 13 deletions(-)

diff --git a/Makefile b/Makefile
index a3fe4eb..b833ce3 100644
--- a/Makefile
+++ b/Makefile
@@ -1,24 +1,42 @@
-SHELL=/bin/bash
-mlbuf_cflags:=$(CFLAGS) -D_GNU_SOURCE -Wall -g -fPIC
-mlbuf_ldlibs:=$(LDLIBS) -lpcre
-mlbuf_objects:=$(patsubst %.c,%.o,$(wildcard *.c))
+SHELL ?= /bin/bash
 
-all: libmlbuf.so
+LIBNAME = libmlbuf
+LIB_VER_MAJOR = 0
+LIB_VER_MINOR = 0
+LIB_VER_PATCH = 1
+LIB_VER = $(LIB_VER_MAJOR).$(LIB_VER_MINOR).$(LIB_VER_PATCH)
 
-libmlbuf.so: libmlbuf.a
-	$(CC) -shared $(mlbuf_ldlibs) -o libmlbuf.so $(mlbuf_objects)
+CFLAGS ?= -g
+CCLD   ?= $(CC)
 
-libmlbuf.a: $(mlbuf_objects)
-	$(AR) rcs libmlbuf.a $(mlbuf_objects)
+CFLAGS  += -D_GNU_SOURCE -Wall -fPIC
+CFLAGS  += $(shell pkg-config libpcre --cflags)
+LDFLAGS += -shared
+LDFLAGS += $(shell pkg-config libpcre --libs-only-L --libs-only-other)
+LDLIBS  += $(shell pkg-config libpcre --libs-only-l)
 
-$(mlbuf_objects): %.o: %.c
-	$(CC) -c $(mlbuf_cflags) $< -o $@
+SRCS    := $(wildcard *.c)
+OBJS    := $(SRCS:.c=.o)
 
-test: libmlbuf.so
+
+all: $(LIBNAME).so $(LIBNAME).a
+
+$(LIBNAME).so: $(OBJS)
+	$(CCLD) $(LDFLAGS) -Wl,-soname,$(LIBNAME).so.$(LIB_VER_MAJOR) -o $(LIBNAME).so.$(LIB_VER) $(OBJS) $(LDLIBS)
+	ln -s $(LIBNAME).so.$(LIB_VER) $(LIBNAME).so.$(LIB_VER_MAJOR).$(LIB_VER_MINOR)
+	ln -s $(LIBNAME).so.$(LIB_VER) $(LIBNAME).so.$(LIB_VER_MAJOR)
+	ln -s $(LIBNAME).so.$(LIB_VER) $(LIBNAME).so
+
+$(LIBNAME).a: $(OBJS)
+	$(AR) rcs $(LIBNAME).a $(OBJS)
+
+$(OBJS): %.o: %.c
+
+test: $(LIBNAME).so
 	$(MAKE) -C tests
 
 clean:
-	rm -f *o libmlbuf.a libmlbuf.so
+	$(RM) -f *.o $(LIBNAME).a $(LIBNAME).so*
 	$(MAKE) -C tests clean
 
 .PHONY: all test clean
